##################################
### START headder common parts ###
##################################
in:
  type: gcs
  bucket: ${td.each.col02}
  path_prefix: ${td.each.col03}_${session_date_compact}
  auth_method: json_key
  json_keyfile: 
    content: ${secret:gcp.credential}
  parser:
    type: ${karte.parser.type}
    delimiter: ${karte.parser.delimiter}
    quote: ${karte.parser.quote}
    escape: ${karte.parser.escape}
    skip_header_lines: ${karte.parser.skip_header_lines}
    null_string: ${karte.parser.null_string}
    newline: ${karte.parser.newline}
    charset: ${karte.parser.charset}
    trim_if_not_quoted: ${karte.parser.trim_if_not_quoted}
    max_quoted_size_limit: ${karte.parser.max_quoted_size_limit}
    default_timezone: ${karte.parser.default_timezone}
    allow_optional_columns: ${karte.parser.allow_optional_columns}
    allow_extra_columns: ${karte.parser.allow_extra_columns}
    stop_on_invalid_record: ${karte.parser.stop_on_invalid_record}
################################
### END headder common parts ###
################################

    columns:
    - {name: mkdb_id, type: string}
    - {name: flag, type: string}
    - {name: view, type: string}
    - {name: click, type: string}
    - {name: click_url, type: string}

################################
### START filter common parts ##
################################
filters:
- type: add_time
  from_value:
    mode: upload_time
  to_column:
    name: time
##############################
### END filter common parts ##
##############################


################################
### START footer common parts ##
################################
out: 
  type: td
  mode: ${td.each.col06}
##############################
### END footer common parts ##
##############################