# karte settings
karte:
  parser:
    type: csv
    delimiter: "\",\""
    quote: "\"\\\"\""
    escape: "\"\\\"\""
    skip_header_lines: 1
    null_string: "\"\""
    newline: CRLF
    charset: UTF-8
    trim_if_not_quoted: false
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false