# process name
process_name: h2o_hitmall_import_calculate

# pro or stg
mode: stg

# send mail mode true/false
mail:
  # start mail
  send_start: true
  # success mail
  send_end: true
  # sla mail
  send_sla: true

# Record Process Status
record_process:
  status:
    # ${init.record_process.status.start}
    start: "START"
    # ${init.record_process.status.end}
    end: "END"
    # ${init.record_process.status.error}
    error: "ERROR"
    # ${init.record_process.status.warning}
    warning: "WARNING"
  name:
    # ${init.record_process.name.common}
    common: "__GLOBAL__"