# process settingss
process:

  # loop calculate data setting
  loop_process_data:

    # digs/calculate_data file list
    task_list: 
      - loop_process_data_task01.dig

# SFTP settings
sftp:
  user_directory_is_root: false
  timeout: 600
  retry: 2
  parser:
    type: csv
    delimiter: "\",\""
    quote: "\"\\\"\""
    escape: "\"\\\"\""
    skip_header_lines: 1
    null_string: "\"\""
    newline: LF
    charset: UTF-8
    trim_if_not_quoted: false
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false
