##################################
### START headder common parts ###
##################################
in:
  type: sftp
  host: ${secret:sftp.host}
  user: ${secret:sftp.user}
  port: ${secret:sftp.port}
  # password: 
  secret_key_passphrase: ${secret:sftp.secret_key_passphrase}
  secret_key_file: 
    content: |
      ${secret:sftp.secret_key_file}
  user_directory_is_root: false
  timeout: 600
  max_connection_retry: 2
  path_prefix: "/tduser/send/m_svc_acct_profile_migration"
  parser:
    type: csv
    delimiter: ","
    quote: "\""
    escape: null
    skip_header_lines: 0
    null_string: ""
    newline: LF
    charset: EUC-JP
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false
################################
### END headder common parts ###
################################

    columns:
    - {name: mkdb_id, type: string}
    - {name: base_month, type: string}
    - {name: profile_name, type: string}
    - {name: profile_value, type: string}
    - {name: ts, type: string}

################################
### START filter common parts ##
################################
filters:
- type: add_time
  to_column:
    name: time
    type: timestamp
  from_value:
    value: ${session_unixtime}
##############################
### END filter common parts ##
##############################


################################
### START footer common parts ##
################################
out: 
  type: td
  mode: append
##############################
### END footer common parts ##
##############################