drop table if exists ${td.each.col02}.${td.each.col03};
create table ${td.each.col02}.${td.each.col03} as

select
    mkdb_id
  , base_month
  , uai_acct_del_flg
  , uai_dealer_number
  , uai_star_user_code
  , uai_star_account
  , uai_internet_kbn
  , uai_corporation_kbn
  , uai_zip_code_first
  , uai_zip_code_last
  , uai_address_kanji1
  , uai_address_kana1
  , uai_address_status
  , uai_address_update
  , uai_occupation
  , uai_phone_flg
  , uai_sex_kbn
  , uai_birth_era
  , uai_birth_date
  , uai_birth_day
  , uai_all_acct_close
  , uai_f_relationship
  , uai_f_relationship_others
  , uai_f_relationship_occpation
  , uai_f_relationship_executive
  , uai_f_relationship_position_na
  , uai_office_after_kbn
  , uai_office_occpation
  , uai_office_presentation
  , uai_office_executive
  , uai_office_position_name
  , uai_office_zip_code_first
  , uai_office_zip_code_last
  , uai_office_address_kanji1
  , uai_office_daihyo_kbn
  , uai_office_dairi_kbn
  , uai_insider_kbn
  , uai_bank_type_kbn
  , uai_bank_post_kbn
  , uai_bank_date
  , uai_currency_code
  , uai_qa_investment_plan
  , uai_qa_investment_plan_other
  , uai_qa_fund_character
  , uai_qa_fund_character_other
  , uai_qa_income_form
  , uai_qa_income_form_other
  , uai_qa_trading_motive
  , uai_qa_trading_motive_other
  , uai_qa_employment_period
  , uai_qa_employment_period_other
  , uai_qa_annual_income
  , uai_qa_financial_assets
  , uai_qa_interested_trading
  , uai_qa_interested_trading_othe
  , uai_exp_stock_kbn
  , uai_exp_stock
  , uai_exp_stock_status
  , uai_exp_debenture_kbn
  , uai_exp_debenture
  , uai_exp_debenture_status
  , uai_exp_cb_kbn
  , uai_exp_cb
  , uai_exp_cb_status
  , uai_exp_margin_kbn
  , uai_exp_margin
  , uai_exp_margin_status
  , uai_exp_warrant_kbn
  , uai_exp_warrant
  , uai_exp_warrant_status
  , uai_exp_futureop_kbn
  , uai_exp_futureop
  , uai_exp_futureop_status
  , uai_exp_savedtypefund_kbn
  , uai_exp_savedtypefund
  , uai_exp_savedtypefund_status
  , uai_exp_otherfund_kbn
  , uai_exp_otherfund
  , uai_exp_otherfund_status
  , uai_exp_foreign_kbn
  , uai_exp_foreign
  , uai_exp_foreign_status
  , uai_exp_other_name
  , uai_exp_other_kbn
  , uai_exp_other
  , uai_exp_other_status
  , uai_corp_capital
  , uai_corp_organization_kbn1
  , uai_corp_organization_kbn2
  , uai_corp_settlement_term1
  , uai_corp_settlement_term2
  , uai_corp_procedure_kbn
  , uai_corp_bank_kbn
  , uai_corp_address_kanji1
  , uai_corp_address_kana1
  , uai_acct_status
  , uai_acct_class_flg1
  , uai_acct_class_flg2
  , uai_open_acct_date
  , uai_specific_kbn
  , uai_specific_start_date
  , uai_specific_stop_date
  , uai_specific_m_kbn
  , uai_update
  , uai_nationality
  , uai_greencard_hold
  , uai_us_resident
  , uai_resident_code
  , uai_non_resident
  , uai_naigai_corp_kbn
  , uai_qi_ctgry_bunrui1
  , uai_qi_ctgry_bunrui2
  , uai_dm_bank_deposit_class
  , uai_f_relation_birth_era
  , uai_f_relation_birth_date
  , uai_f_relation_birth_day
  , uai_f_relation_office_code
  , uai_f_relation_office_present
  , uai_prefecture_code
  , uai_specific_dividend_start_dt
  , uai_specific_dividend_end_dt
  , uai_interest_get_kbn
  , uai_interest_country_kbn
  , uai_interest_goods_kbn
  , uai_interest_goods_sts1
  , uai_interest_goods_sts2
  , uai_interest_company_code
  , uai_interest_right_kbn
  , uai_interest_oan_kbn
  , uai_interest_frequency
  , uai_interest_gou1
  , uai_interest_gou2
  , uai_interest_country_code
  , uai_distribution_get_kbn
  , uai_distribution_country_kbn
  , uai_distribution_goods_kbn
  , uai_distribution_goods_sts1
  , uai_distribution_goods_sts2
  , uai_distribution_company_code
  , uai_distribution_right_kbn
  , uai_distribution_oan_kbn
  , uai_distribution_frequency
  , uai_distribution_gou1
  , uai_distribution_gou2
  , uai_distribution_country_code
  , uai_zei_kbn_kokunai
  , uai_zei_kbn_gaikabu
  , uai_zei_kbn_gaisai
  , uai_risk_kbn_kabu
  , uai_risk_kbn_sai
  , uai_risk_kbn_tensha
  , uai_risk_kbn_gaisho
  , uai_maruyu_tekikakusha_kbn
  , uai_tokuyu_tekikakusha_kbn
  , uai_houkatsudoui_date
  , uai_isa_contract_kbn
  , uai_isa_buy_current_year_kbn
  , uai_isa_buy_next_year_kbn
  , uai_shibo_date
  , uai_isa_apply_status
  , uai_isa_apply_status_before
  , uai_isa_receipt_date
  , uai_isa_apply_date
  , uai_isa_open_date
  , uai_isa_close_date
  , uai_personal_specific_key
  , uai_number_registration_state
  , uai_corporation_number
  , uai_number_acceptance_state
  , uai_naikoku_hojin_info
  , uai_jnisa_koza_kbn
  , uai_jnisa_mkdb_id
  , uai_jnisa_koza_no_new
  , uai_jnisa_moto_mkdb_id
  , uai_jnisa_moto_koza_no_new
  , uai_jnisa_seigen_shuryo_ymd
  , uai_jnisa_departure_date
  , uai_jnisa_return_home_date
  , uai_jnisa_sinsei_st
  , uai_jnisa_sinsei_st_bf
  , uai_jnisa_uketuke_ymd
  , uai_jnisa_sinsei_ymd
  , uai_jnisa_kaisetsu_ymd
  , uai_jnisa_heisa_ymd
  , uai_jnisa_corp_bank_kbn
  , uai_jnisa_bank_code
  , uai_jnisa_bank_branch_code
  , uai_jnisa_bank_kanji
  , uai_jnisa_bank_branch_kanji
  , uai_jnisa_bank_deposit_class
  , uai_jnisa_bank_account
  , uai_jnisa_bank_account_name
  , uai_jnisa_bank_type_kbn
  , uai_jnisa_bank_post_kbn
  , uai_jnisa_bank_date
  , uai_jnisa_currency_code
  , uai_jnisa_specific_kbn
  , uai_jnisa_specific_start_date
  , uai_jnisa_specific_stop_date
  , uai_jnisa_specific_m_kbn
  , uai_jnisa_fd_bank_code
  , uai_jnisa_fd_bank_branch_code
  , uai_jnisa_fd_bank_kanji
  , uai_jnisa_fd_bank_branch_kanji
  , uai_jnisa_fd_bank_dep_class
  , uai_jnisa_fd_bank_account
  , uai_jnisa_fd_bank_account_name
  , uai_jnisa_dm_transfer_form
  , uai_jnisa_dm_bank_code
  , uai_jnisa_dm_bank_branch_code
  , uai_jnisa_dm_bank_kanji
  , uai_jnisa_dm_bank_branch_kanji
  , uai_jnisa_dm_bank_dep_class
  , uai_jnisa_dm_bank_account
  , uai_jnisa_dm_bank_account_name
  , uai_jnisa_member_account_no
  , uai_jnisa_member_account_code
  , uai_jnisa_prefecture_code
  , uai_jnisa_specific_div_st_dt
  , uai_jnisa_specific_div_ed_dt
  , uai_jnisa_interest_get_kbn
  , uai_jnisa_interest_country_kbn
  , uai_jnisa_interest_goods_kbn
  , uai_jnisa_interest_goods_sts1
  , uai_jnisa_interest_goods_sts2
  , uai_jnisa_interest_company_cd
  , uai_jnisa_interest_right_kbn
  , uai_jnisa_interest_oan_kbn
  , uai_jnisa_interest_frequency
  , uai_jnisa_interest_gou1
  , uai_jnisa_interest_gou2
  , uai_jnisa_interest_country_cd
  , uai_jnisa_distribution_get_kbn
  , uai_jnisa_dist_country_kbn
  , uai_jnisa_distribut_goods_kbn
  , uai_jnisa_distribut_goods_sts1
  , uai_jnisa_distribut_goods_sts2
  , uai_jnisa_distribut_company_cd
  , uai_jnisa_distribut_right_kbn
  , uai_jnisa_distribution_oan_kbn
  , uai_jnisa_distribut_frequency
  , uai_jnisa_distribution_gou1
  , uai_jnisa_distribution_gou2
  , uai_jnisa_distribut_country_cd
  , uai_jnisa_contract_kbn
  , uai_jnisa_buy_current_year_kbn
  , uai_jnisa_buy_next_year_kbn
  , uai_jnisa_perso_specific_key
  , uai_jnisa_number_regist_state
  , uai_jnisa_num_acceptance_state
  , uai_number_upd_kbn
  , uai_number_upd_date
  , uai_jnisa_number_upd_kbn
  , uai_jnisa_number_upd_date
  , uai_bank_code
  , uai_bank_branch_code
  , uai_bank_kanji
  , uai_bank_branch_kanji
  , uai_bank_deposit_class
  , uai_dm_transfer_form
  , uai_dm_bank_code
  , uai_dm_bank_branch_code
  , uai_dm_bank_kanji
  , uai_dm_bank_branch_kanji
  , sitecatalys_hash_value
from
  ${td.each.col05}.${td.each.col06}
where
  -- 最新のデータを対象
  td_time_range(
      time
    , (select max(time) from ${td.each.col05}.${td.each.col06})
    , null
    , 'JST'
  )
  -- mkdb_id is nullは紐付かないので除外
  and mkdb_id is not null
  -- 口座閉鎖フラグが0のユーザのみ
  and uai_acct_del_flg = '0'