##################################
### START headder common parts ###
##################################
in:
  type: sftp
  host: ${sftp.host}
  user: ${sftp.user}
  port: ${sftp.port}
  # password: 
  secret_key_passphrase: ${sftp.secret_key_passphrase}
  secret_key_file: 
    content: |
      ${sftp.secret_key_file}
  user_directory_is_root: ${sftp.user_directory_is_root}
  timeout: ${sftp.timeout}
  max_connection_retry: ${sftp.retry}
  path_prefix: "${td.each.in_filepath}"
  parser:
    type: csv
    delimiter: ,
    quote: "\""
    escape: "¥"
    skip_header_lines: 0
    null_string: ""
    newline: LF
    charset: EUC-JP
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false
################################
### END headder common parts ###
################################

    columns:
    - {name: mkdb_id, type: string}
    - {name: cannel, type: string}
    - {name: base_month, type: string}
    - {name: base_date, type: string}
    - {name: login_date, type: string}
    - {name: logout_date, type: string}
    - {name: remarks1, type: string}
    - {name: remarks2, type: string}
    - {name: remarks3, type: string}
    - {name: remarks4, type: string}
    - {name: remarks5, type: string}

################################
### START footer common parts ##
################################
filters:
- type: add_time
  from_value:
    mode: upload_time
  to_column:
    name: time

out: 
  type: td
  mode: ${td.each.out_mode}
##############################
### END footer common parts ##
##############################