##################################
### START headder common parts ###
##################################
in:
  type: sftp
  host: ${sftp.host}
  user: ${sftp.user}
  port: ${sftp.port}
  # password: 
  secret_key_passphrase: ${sftp.secret_key_passphrase}
  secret_key_file: 
    content: |
      ${sftp.secret_key_file}
  user_directory_is_root: ${sftp.user_directory_is_root}
  timeout: ${sftp.timeout}
  max_connection_retry: ${sftp.retry}
  path_prefix: "${td.each.in_filepath}"
  parser:
    type: csv
    delimiter: ,
    quote: null
    escape: null
    skip_header_lines: 0
    null_string: ""
    newline: LF
    charset: EUC-JP
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false
################################
### END headder common parts ###
################################

    columns:
    - {name: mkdb_id, type: string}
    - {name: base_month, type: string}
    - {name: dealer_no, type: string}
    - {name: application_date, type: string}
    - {name: birthday_gen, type: string}
    - {name: birthday, type: string}
    - {name: sex, type: string}
    - {name: blood_relation_cd, type: string}
    - {name: zip_cd1, type: string}
    - {name: zip_cd2, type: string}
    - {name: address_cd, type: string}
    - {name: address_kana1, type: string}
    - {name: address_kanji1, type: string}
    - {name: tokutei_koza, type: string}
    - {name: finance_name, type: string}
    - {name: receipt_no, type: string}
    - {name: cust_invenstment, type: string}
    - {name: cust_capital, type: string}
    - {name: cust_income, type: string}
    - {name: cust_tran, type: string}
    - {name: cust_oprate, type: string}
    - {name: cust_annual_income, type: string}
    - {name: cust_finance, type: string}
    - {name: cust_interest, type: string}
    - {name: trade_equity, type: string}
    - {name: trade_bond, type: string}
    - {name: trade_bondfund, type: string}
    - {name: trade_margine, type: string}
    - {name: trade_warrant, type: string}
    - {name: trade_futuresoption, type: string}
    - {name: trade_saving_inventment_trust, type: string}
    - {name: trade_other_inventment_trust, type: string}
    - {name: trade_foreign_securities, type: string}
    - {name: confirmation, type: string}
    - {name: create_date, type: string}
    - {name: id_cd, type: string}
    - {name: url_route, type: string}
    - {name: send_customer_id, type: string}
    - {name: open_date, type: string}
    - {name: three_flg, type: string}
    - {name: close_date, type: string}
    - {name: route, type: string}
    - {name: agent_id, type: string}
    - {name: judge_status, type: string}
    - {name: parental_minor_kbn, type: string}
    - {name: deal_subject_person, type: string}
    - {name: household_birthday_gen, type: string}
    - {name: household_birthday, type: string}
    - {name: nationality, type: string}
    - {name: greencard_hold, type: string}
    - {name: us_resident, type: string}
    - {name: investor_kbn, type: string}
    - {name: member_foreign_kbn_ntt, type: string}
    - {name: member_foreign_kbn_broadcast, type: string}
    - {name: member_foreign_kbn_aviation, type: string}
    - {name: qi_category_1, type: string}
    - {name: qi_category_2, type: string}
    - {name: transfer_method, type: string}
    - {name: div_bank_code, type: string}
    - {name: div_bank_name, type: string}
    - {name: div_bank_deposit_class, type: string}
    - {name: div_bank_account_class, type: string}
    - {name: resident_prefecture_code, type: string}
    - {name: sp_dividend_accept, type: string}

################################
### START footer common parts ##
################################
filters:
- type: add_time
  from_value:
    mode: upload_time
  to_column:
    name: time

out: 
  type: td
  mode: ${td.each.out_mode}
##############################
### END footer common parts ##
##############################