##################################
### START headder common parts ###
##################################
in:
  type: sftp
  host: ${sftp.host}
  user: ${sftp.user}
  port: ${sftp.port}
  # password: 
  secret_key_passphrase: ${sftp.secret_key_passphrase}
  secret_key_file: 
    content: |
      ${sftp.secret_key_file}
  user_directory_is_root: ${sftp.user_directory_is_root}
  timeout: ${sftp.timeout}
  max_connection_retry: ${sftp.retry}
  path_prefix: "${td.each.in_filepath}"
  parser:
    type: csv
    delimiter: ,
    quote: null
    escape: null
    skip_header_lines: 0
    null_string: ""
    newline: LF
    charset: EUC-JP
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false
################################
### END headder common parts ###
################################

    columns:
    - {name: mkdb_id, type: string}
    - {name: input_file_id1, type: string}
    - {name: input_file_id2, type: string}
    - {name: group_id, type: string}
    - {name: class_code, type: string}
    - {name: support_class, type: string}
    - {name: i_user_code, type: string}
    - {name: record_date, type: string}
    - {name: self_div, type: string}
    - {name: dealer_code, type: string}
    - {name: occupation1, type: string}
    - {name: occupation2, type: string}
    - {name: internet_kbn, type: string}
    - {name: hoyu_koza_g1, type: string}
    - {name: isa_dealer_code, type: string}
    - {name: kaituke_y, type: string}
    - {name: shori_ymd, type: string}
    - {name: isa_keiyaku_kbn, type: string}
    - {name: isa_hkzwk_gendo_gk, type: string}
    - {name: isa_hkzwk_shiyo_gk_fugo, type: string}
    - {name: isa_hkzwk_shiyo_gk, type: string}
    - {name: isa_wkover_ymd, type: string}
    - {name: nisa_shur, type: string}

################################
### START footer common parts ##
################################
filters:
- type: add_time
  from_value:
    mode: upload_time
  to_column:
    name: time

out: 
  type: td
  mode: ${td.each.out_mode}
##############################
### END footer common parts ##
##############################