s3:
  path_match_pattern: _${moment(session_time).format("YYYYMMDD")}.csv$
  parser:
    type: csv
    delimiter: "\",\""
    quote: "\"\\\"\""
    escape: "\"\\\\\""
    skip_header_lines: 0  
    null_string: "\"\""
    newline: CRLF
    charset: UTF-8
    trim_if_not_quoted: false
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false

# file importy init settings
file:
  user_directory_is_root: false
  timeout: 600
  retry: 2
  parser:
    type: csv
    delimiter: "\",\""
    quote: "\"\\\"\""
    escape: "\"\\\"\""
    skip_header_lines: 1
    null_string: "\"\""
    newline: LF
    charset: UTF-8
    trim_if_not_quoted: false
    max_quoted_size_limit: 131072
    default_timezone: Asia/Tokyo
    allow_optional_columns: false
    allow_extra_columns: false
    stop_on_invalid_record: false